# Generated by Django 5.1.2 on 2024-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.CreateModel(
            name='Pesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('peso', models.IntegerField()),
            ],
        ),
    
    ]
